// <auto-generated />
using System;
using Audit.Infrastructure.Persistence.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Audit.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(FuellerDbContext))]
    [Migration("20240630105240_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Audit.Domain.Model.Forecourt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Forecourts", (string)null);
                });

            modelBuilder.Entity("Audit.Domain.Model.Lane", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ForecourtId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ForecourtId");

                    b.ToTable("Lanes", (string)null);
                });

            modelBuilder.Entity("Audit.Domain.Model.Lane", b =>
                {
                    b.HasOne("Audit.Domain.Model.Forecourt", null)
                        .WithMany("Lanes")
                        .HasForeignKey("ForecourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Audit.Domain.Model.Forecourt", b =>
                {
                    b.Navigation("Lanes");
                });
#pragma warning restore 612, 618
        }
    }
}
